### ISSUE TITLE
Fixed minimum dimensions

### ISSUE THREAD

**Issue by SimonMeili** [Oshan96/CustomStage#12]
If we create a stage which is smaller than 259x700 it gets resized to 259x700 the first time a user tries to change the window size manually (by dragging the edges of the window). 

We suspect the error to be in lk.vivoxalabs.customstage.tools.ResizeHelper:17. Is there a specific reason for fixing the minimum dimensions to 259x700?

**Comment by Oshan96** [comment]
Hi there @SimonMeili ! 
I think the issue you're having that issue because you're not explicitly declaring minimum dimensions of your stage so the stage is created with 259x700 minimum dimensions, by default(as it is in lk.vivoxalabs.customstage.tools.ResizeHelper:17).
However, you can override these minimum 259x700 dimension cap if you use `setDimensions(double minWidth,double minHeight,double maxWidth,double maxHeight)` method which is provided in [CustomStageBuilder](https://github.com/Oshan96/CustomStage/blob/master/src/main/java/lk/vivoxalabs/customstage/CustomStageBuilder.java) class.

As for an example, you can create your customstage with 200x200 minimum dimensions like this;
```java
CustomStage stage = new CustomStageBuilder()
    .setDimensions(200,200,1920,1280)
    .build();
```

Hope this will fix it for you! :)
Checkout the detailed [wiki](https://github.com/Oshan96/CustomStage/wiki) page so you can actually learn how to use CustomStage upto it's fully capabilities!
And you can see all these different ways to build your CustomStage if you go through the sample codes in [examples](https://github.com/Oshan96/CustomStage/tree/master/examples) directory.
Also you can use the [CustomStage API](https://oshan96.github.io/CustomStage/) as well for further info.
